<?php

namespace Plugin\PayPalExpress\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PayPalExpressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayPalExpressRepository extends EntityRepository
{
}